#+TITLE: Programmation synchrone 2022/2023 -- Journal du cours
#+AUTHOR: Adrien Guatto
#+EMAIL: guatto@irif.org
#+LANGUAGE: fr
#+OPTIONS: ^:nil p:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \hypersetup{hidelinks}
#+LATEX_HEADER: \usepackage[french]{babel}
# (org-latex-export-to-pdf)

  Ce fichier est disponible au
  [[https://www.irif.fr/~guatto/teaching/22-23/progsync/journal.html][format
  HTML]].
* Cours 1 <2022-09-27>
  On lit le syllabus, les notes jusqu'à la page 10.

  Le site d'Heptagon n'est plus disponible, mais le manuel peut être trouvé sur
  le dépôt du compilateur. On peut cliquer sur le bouton /download/ pour
  télécharger une copie PDF.

  https://gitlab.inria.fr/synchrone/heptagon/-/blob/ec26be27b91f3e601b98b8b7e15e8d56d4b9afc7/manual/heptagon-manual.pdf
* Cours 2 <2022-10-04>
  On lit les notes jusqu'à la page 16.
* Cours 3 <2022-10-11>
  On lit les notes jusqu'à la page 23.
* Cours 4 <2022-10-18>
  On lit les notes jusqu'à la page 31.
* Cours 5 <2022-10-25>
  On lit les notes jusqu'à la page 38.
* Cours 6 <2022-11-08>
  On discute du projet. Le code et le sujet peuvent être trouvés dans le
  répertoire [[file:../projet/][projet]].

  Pour réaliser le projet, il faut un compte sur Gaufre, le serveur GitLab de
  l'UFR d'informatique.

  https://gaufre.informatique.univ-paris-diderot.fr/

  Si vous avez déjà un compte à l'UFR d'informatique, celui-ci permet de vous
  connecter à Gaufre. C'est notamment le cas de tous les étudiants de M2. Pour
  les étudiants de l'EIDD, je suis en train de faire le nécessaire ; je vous
  tiens au courant d'ici à la semaine prochaine.
